import React from 'react';
import { motion } from 'framer-motion';

const CTAFooter = ({ data, variant = 'centered' }) => {
  const isMinimal = variant === 'minimal';
  const isSplit = variant === 'split';

  if (isMinimal) {
    return (
      <footer className="py-12 px-6 border-t border-white/5 bg-[var(--bg-page)] text-[var(--text-main)]">
        <div className="max-w-7xl mx-auto flex flex-col md:flex-row justify-between items-center gap-6">
          <div className="text-2xl font-bold tracking-tight">{data?.text?.split(' ')[0] || "Marca"}</div>
          <div className="flex gap-8 text-sm opacity-60">
            <span>Instagram</span>
            <span>Twitter</span>
            <span>Email</span>
          </div>
          <p className="text-xs opacity-40">© {new Date().getFullYear()} All rights reserved.</p>
        </div>
      </footer>
    );
  }

  if (isSplit) {
    return (
      <footer className="py-24 px-6 bg-[var(--surface)] text-[var(--text-main)]">
        <div className="max-w-7xl mx-auto grid md:grid-cols-2 gap-12 items-center">
          <div>
            <h2 className="text-4xl md:text-6xl font-bold mb-6">{data?.text}</h2>
            <button 
              className="px-8 py-4 rounded-full font-bold text-lg hover:scale-105 transition-transform" 
              style={{ backgroundColor: 'var(--primary)', color: 'var(--bg-page)' }}
            >
              {data?.button_text || "Contact Us"}
            </button>
          </div>
          <div className="grid grid-cols-2 gap-8 text-sm opacity-70">
             <div className="flex flex-col gap-4">
                <span className="font-bold text-base opacity-100">Social</span>
                <span>Instagram</span>
                <span>LinkedIn</span>
                <span>Twitter</span>
             </div>
             <div className="flex flex-col gap-4">
                <span className="font-bold text-base opacity-100">Legal</span>
                <span>Privacy Policy</span>
                <span>Terms of Service</span>
             </div>
          </div>
        </div>
      </footer>
    );
  }

  // DEFAULT: Centered High Impact
  return (
    <footer className="py-32 px-4 text-center bg-[var(--bg-page)] relative overflow-hidden">
      <div className="absolute inset-0 opacity-20 pointer-events-none" 
           style={{ background: `radial-gradient(circle at center, var(--primary), transparent 70%)` }} 
      />
      
      <div className="relative z-10 max-w-4xl mx-auto">
        <motion.h2 
          initial={{ opacity: 0, y: 20 }}
          whileInView={{ opacity: 1, y: 0 }}
          className="text-5xl md:text-7xl font-bold mb-10 tracking-tight"
          style={{ color: 'var(--text-main)' }}
        >
          {data?.text || "Ready to start?"}
        </motion.h2>
        
        <motion.button
          whileHover={{ scale: 1.05 }}
          whileTap={{ scale: 0.95 }}
          className="px-10 py-4 rounded-full text-xl font-bold transition-all shadow-xl"
          style={{ backgroundColor: 'var(--primary)', color: 'var(--bg-page)' }}
        >
          {data?.button_text || "Get Started"}
        </motion.button>
        
        <div className="mt-20 pt-10 border-t border-white/10 text-sm flex justify-between items-center opacity-50" style={{ color: 'var(--text-main)' }}>
          <p>© {new Date().getFullYear()} Generated by Syncelle.</p>
          <div className="flex gap-4">
            <span>Privacy</span>
            <span>Terms</span>
          </div>
        </div>
      </div>
    </footer>
  );
};

export default CTAFooter;

