import React from 'react';
import { motion } from 'framer-motion';

const CTAFooter = ({ data }) => {
  return (
    <footer className="py-32 px-4 text-center bg-zinc-950 relative overflow-hidden">
      <div className="absolute inset-0 bg-[radial-gradient(circle_at_center,_var(--tw-gradient-stops))] from-emerald-900/20 via-transparent to-transparent pointer-events-none" />
      
      <div className="relative z-10 max-w-4xl mx-auto">
        <motion.h2 
          initial={{ opacity: 0, y: 20 }}
          whileInView={{ opacity: 1, y: 0 }}
          className="text-5xl md:text-7xl font-bold text-white mb-10 tracking-tight"
        >
          {data?.text || "Ready to start?"}
        </motion.h2>
        
        <motion.button
          whileHover={{ scale: 1.05 }}
          whileTap={{ scale: 0.95 }}
          className="bg-white text-black px-10 py-4 rounded-full text-xl font-bold hover:bg-emerald-400 transition-colors"
        >
          {data?.button_text || "Get Started"}
        </motion.button>
        
        <div className="mt-20 pt-10 border-t border-white/10 text-zinc-500 text-sm flex justify-between items-center">
          <p>© 2024 Generated by Syncelle.</p>
          <div className="flex gap-4">
            <span>Privacy</span>
            <span>Terms</span>
          </div>
        </div>
      </div>
    </footer>
  );
};

export default CTAFooter;

