'use client';

import React from 'react';
import BentoGrid from './blocks/BentoGrid';
import Marquee from './blocks/Marquee';
import Narrative from './blocks/Narrative';
import Showcase from './blocks/Showcase';
import CTAFooter from './blocks/CTAFooter';
import { motion } from 'framer-motion';

const fallbackImage = "https://images.unsplash.com/photo-1527254059249-05af64a0bc3f?auto=format&fit=crop&w=1600&q=80";

const NavbarBlock = ({ data, variant }) => {
  const style = variant || "topbar";
  const base = "w-full max-w-6xl mx-auto flex items-center justify-between px-6 py-3";
  const glass = "backdrop-blur-xl bg-black/60 border border-white/10 rounded-full";
  const topbar = "border-b border-white/10";
  const floating = "rounded-full shadow-xl bg-black/70 border border-white/10 px-6";
  const cls = style === "glass" ? glass : style === "floating" ? floating : topbar;
  const links = data?.links || [];
  return (
    <nav className={`sticky top-0 z-40 text-white ${style === "topbar" ? "bg-black/60 backdrop-blur" : "bg-transparent"}`}>
      <div className={`${base} ${cls}`}>
        <div className="flex items-center gap-3">
          <span className="w-9 h-9 rounded-lg bg-emerald-500 flex items-center justify-center font-bold text-black">S</span>
          <span className="font-bold text-lg">{data?.brand || "Syncelle"}</span>
        </div>
        <div className="hidden md:flex items-center gap-6 text-sm">
          {links.map((l, i) => (
            <a key={i} href={l.href} className="hover:text-emerald-400 transition-colors">{l.label}</a>
          ))}
          {data?.cta && (
            <a href="/dashboard" className="px-4 py-2 rounded-full bg-white text-black font-semibold hover:scale-105 transition">
              {data.cta}
            </a>
          )}
        </div>
      </div>
    </nav>
  );
};

const BlockRegistry = {
  'navbar': NavbarBlock,
  'hero': ({ data, variant }) => {
    const bgImage = data?.image_url || fallbackImage;
    
    // VARIANT: SPLIT (Texto Izq / Imagen Der)
    if (variant === 'split') {
      return (
        <section className="min-h-screen w-full flex items-center justify-center p-6 md:p-12 relative overflow-hidden bg-[var(--bg-page)]">
           <div className="max-w-7xl w-full grid grid-cols-1 lg:grid-cols-2 gap-12 items-center relative z-10">
              <motion.div 
                initial={{ opacity: 0, x: -50 }}
                whileInView={{ opacity: 1, x: 0 }}
                viewport={{ once: true }}
                transition={{ duration: 0.8 }}
                className="text-left"
              >
                  <h1 className="text-5xl md:text-7xl font-bold mb-6 tracking-tighter leading-tight" style={{ color: 'var(--text-main)' }}>
                    {data?.headline}
                  </h1>
                  <p className="text-xl md:text-2xl opacity-70 mb-8 font-light leading-relaxed" style={{ color: 'var(--text-main)' }}>
                    {data?.subheadline}
                  </p>
                  <div className="flex gap-4">
                     {data?.cta_primary && (
                        <button className="px-8 py-4 rounded-full font-bold text-lg hover:scale-105 transition-transform" style={{ backgroundColor: 'var(--primary)', color: 'black' }}>
                           {data.cta_primary}
                        </button>
                     )}
                  </div>
              </motion.div>

              <motion.div 
                 initial={{ opacity: 0, scale: 0.9, rotate: -2 }}
                 whileInView={{ opacity: 1, scale: 1, rotate: 0 }}
                 viewport={{ once: true }}
                 transition={{ duration: 0.8, delay: 0.2 }}
                 className="relative h-[500px] w-full rounded-3xl overflow-hidden shadow-2xl"
              >
                 <img src={bgImage} alt="Hero Visual" className="object-cover w-full h-full" />
                 {/* Glass overlay en la esquina */}
                 <div className="absolute bottom-6 left-6 right-6 p-6 glass-panel rounded-2xl">
                    <p className="text-sm text-white/80 font-mono">Generated by Syncelle AI</p>
                 </div>
              </motion.div>
           </div>
        </section>
      );
    }

    // VARIANT: DEFAULT (Centered Cinematic)
    return (
      <section className="min-h-screen w-full flex flex-col justify-center items-center relative overflow-hidden px-4 md:px-8 pt-20">
        {/* Capa de Imagen de Fondo con Parallax suave */}
        <motion.div 
          initial={{ scale: 1.1, opacity: 0 }}
          animate={{ scale: 1, opacity: 1 }}
          transition={{ duration: 1.5, ease: "easeOut" }}
          className="absolute inset-0 z-0"
        >
          <div 
            className="absolute inset-0 bg-cover bg-center bg-no-repeat"
            style={{ backgroundImage: `url('${bgImage}')` }}
          />
          <div className="absolute inset-0 bg-black/50 backdrop-blur-[2px]" />
          <div className="absolute inset-0 bg-gradient-to-t from-[var(--bg-page)] via-[var(--bg-page)]/50 to-transparent" />
        </motion.div>
        
        {/* Contenido Centrado */}
        <div className="relative z-10 max-w-5xl mx-auto text-center flex flex-col items-center">
          {/* ... resto del contenido centrado ... */}
          <motion.h1 
            initial={{ opacity: 0, y: 50, filter: 'blur(10px)' }}
            animate={{ opacity: 1, y: 0, filter: 'blur(0px)' }}
            transition={{ duration: 0.8, ease: "easeOut" }}
            className="text-5xl md:text-7xl lg:text-8xl font-bold mb-8 tracking-tighter leading-[1.1] text-white drop-shadow-2xl"
          >
            {data?.headline || "Diseño sin límites."}
          </motion.h1>

          <motion.p 
            initial={{ opacity: 0 }}
            animate={{ opacity: 1 }}
            transition={{ delay: 0.4, duration: 0.8 }}
            className="text-lg md:text-2xl text-white/80 max-w-2xl font-light mb-10 leading-relaxed shadow-black drop-shadow-md"
          >
            {data?.subheadline || "Creamos experiencias digitales que marcan la diferencia."}
          </motion.p>
          
          <motion.div 
            initial={{ opacity: 0, y: 20 }}
            animate={{ opacity: 1, y: 0 }}
            transition={{ delay: 0.6 }}
            className="flex flex-col sm:flex-row gap-4"
          >
            {data?.cta_primary && (
              <button 
                  className="px-8 py-4 rounded-full font-bold text-lg transition-all hover:scale-105 shadow-[0_0_30px_-5px_var(--primary)] hover:shadow-[0_0_40px_-5px_var(--primary)] active:scale-95"
                  style={{
                    backgroundColor: 'var(--primary)',
                    color: '#000' 
                  }}
              >
                  {data.cta_primary}
              </button>
            )}
            
            {data?.cta_secondary && (
              <button 
                  className="px-8 py-4 rounded-full font-bold text-lg transition-all hover:bg-white/10 border border-white/20 backdrop-blur-md text-white active:scale-95"
              >
                  {data.cta_secondary}
              </button>
            )}
          </motion.div>
        </div>
      </section>
    );
  },
  'bento-grid': BentoGrid,
  'marquee': Marquee,
  'narrative': Narrative,
  'showcase': Showcase,
  'cta-footer': CTAFooter,
};

export default function BlockRenderer({ block, index }) {
  const Component = BlockRegistry[block.type];
  
  if (!Component) {
    return (
      <div className="p-10 border border-red-500/20 bg-red-500/5 m-4 rounded-lg text-red-400 font-mono text-sm">
        [Bloque: {block.type}]
      </div>
    );
  }

  // Pasamos variant y style explícitamente
  return <Component data={block.data} variant={block.variant} style={block.style} />;
}

